-- liquibase formatted sql
-- changeset PK:021-add_fight_stats_to_user.sql
ALTER TABLE users ADD COLUMN wins int NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN loses int NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN skin VARCHAR(100) NOT NULL;

CREATE TABLE skins (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL UNIQUE,
    url VARCHAR(100) NOT NULL UNIQUE,
    requirement INT NOT NULL DEFAULT 0,
    metric VARCHAR(50)
);