-- liquibase formatted sql
-- changeset PK:028-add_coins_column_to_users.sql

ALTER TABLE users ADD COLUMN power_coins INT NOT NULL DEFAULT 0;

CREATE TABLE power_ups (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(150),
    price INT DEFAULT 1,
    type VARCHAR(50) NOT NULL,
    value INT DEFAULT 1
);

CREATE TABLE user_powers (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    power_id INT NOT NULL REFERENCES power_ups(id) ON DELETE CASCADE,
    amount INT NOT NULL DEFAULT 0
);